# site settings
title: Sajag Chauhan
subtitle: DevOps Engineer, ML Enthusiast
email: sajagchauhan7@gmail.com
description: I am a DevOps Engineer working in TCS. I am an ML enthusiast. HTML5 Up<br /> 
baseurl: "Sajag Chauhan" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Niti Khand 3, Indirapuram
city: Ghaziabad
state: UP
zip_code: 201014
country: India
phone: (852) 711-6418

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/SajagChauhan
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/sajagchauhan
  Twitter: https://twitter.com/SajagChauhan
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
